version: "2"
linters:
  settings:
    funlen:
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - lll
          - maligned
          - noctx
          - scopelint
          - staticcheck
        path: _test.go
      - path: (.+)\.go$
        text: pkg/generated
    paths:
      - (^|/)bin($|/)
      - (^|/)examples($|/)
      - (^|/)schemas($|/)
      - (^|/)test-harness($|/)
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
