name: flagd
base: core20
version: 0.7.2
summary: A feature flag daemon with a Unix philosophy
description: >
  Flagd is a simple command line tool for fetching and evaluating feature flags
  for services. It is designed to conform with the OpenFeature specification. 
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64
apps:
  flagd:
    command: bin/flagd
    plugs:
      - home
      - network
      - network-bind
parts:
  home:
    plugin: go
    source-type: git
    source: https://github.com/open-feature/flagd.git
