name: Docker Image CI

on:
  push:
    branches: [ main,feature,feat ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: false
      -
        name: Build
        run: |
          docker build --platform="linux/amd64,linux/arm64" .
