name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  docker-local:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        # volumes:
        #   #- ${{ github.workspace }}/registry:/var/lib/registry
        #   - tmp/registry:/var/lib/registry
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          driver-opts: network=host
          context: .
          driver: docker
          push: true
          #file: ./Dockerfile
          #tags: local/flagd-local:${{ github.event.number }}
          tags: localhost:5000/flagd-local:17
          ##outputs: type=local,dest=/tmp/flagd-local.tar

      - name: Save to file
        run: docker save localhost:5000/flagd-local:17 > /tmp/flagd-local.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          input: /tmp/flagd-local.tar
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
