name: release

on:
  push:
   tags:
    - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      -
        name: Set up Go
        uses: actions/setup-go@v3
      - name: Fetch Deps
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.11.0
          cp schemas/json-schema/flagd-definitions.json pkg/eval/flagd-definitions.json
          oapi-codegen --config=./config/open_api_gen_config.yml ./schemas/openapi/provider.yml
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
